### ISSUE TITLE
Can we use player IDs instead of a player object?

### ISSUE THREAD

**Issue by MiguelEXE** [Kampfkarren/Roblox#162]
I'm writing a economy system in my game, where if the player is not online, it still can receives a transaction from another player, but when i read the documentation, i found that i need a player object to use the datastore system. But if the player is offline, the transaction can't be made, so, can we use a player ID instead of a player object?

**Comment by Kampfkarren** [comment]
There's an open issue for user IDs, but read only. The problem is it's not safe. DataStore2 caches, and so multiple separate instances can end up clashing different data against each other.

I wrote about this problem in detail in this blog post about a separate library I'm on-and-off-writing: https://blog.boyned.com/articles/committing-to-safety-in-data-stores/
