### ISSUE TITLE
Type checking

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/Roblox#27]
All too often I don't catch myself doing `DataStore2(player, "name")` instead of the other way around and DataStore2 doesn't stop me, it just gives a vague error.

**Comment by quackrobloxian** [comment]
Hey @Kampfkarren, I was looking into this ticket and wanted to take a crack at solving it.

Two ideas came to mind, one being simply asserting the arguments provided, and the other being determining whether the two arguments have been swapped around and manually unswapping them, see:

```lua
function DataStore2:__call(dataStoreName, player)
	if typeof(dataStoreName) == "Instance" and typeof(player) == "string" then -- edge case for users providing the :DataStore2() call with incorrectly positioned arguments
		dataStoreName, player = player, dataStoreName
		warn(":DataStore2() API call expected {string dataStoreName, Instance player}, got {Instance player, string dataStoreName}. This may not be supported in the future.")
	end
```

I believe that since DataStore2 doesn't currently support backwards arguments, there'd be no point in implementing option 2.

What do you think?

Cheers.

**Comment by Kampfkarren** [comment]
I'd rather for correctness just error, don't want people just ignoring the warning or not realizing they're getting it if their console is filled with other logs.

**Comment by quackrobloxian** [comment]
Sounds good to me 👍.

**Comment by quackrobloxian** [comment]
Should hopefully be resolved as per PR https://github.com/Kampfkarren/Roblox/pull/33. Let me know if there are any issues.
